### ISSUE TITLE
Make this repo private

### ISSUE THREAD

**Issue by mihhailn** [soramitsukhmer/setup#3]
Is there any reason for this repo to be public ? 
Also since we already have confluence license let's put all documentation (e.g onboarding process) there

**Comment by socheatsok78** [comment]
This repo for setup tools to bootstrap machine. So there is no sensitive info. So there is no need to be private.

**Comment by socheatsok78** [comment]
Check here for more info: https://github.com/soramitsukhmer/setup#what-this-does
